### ISSUE TITLE
Get request does not work on every machine

### ISSUE THREAD

**Issue by LordenGreen** [Programie/node-red-aircon-rac-wf#3]
Hi Programie,
frist of all thank you very much for the very good work and effort you put in this project. I highly appreciate it 👍 
I have 4 Wall units installed and I noticed that I dont get the right status via "getstat" from 2 of them. For the other it 2 work flawlessly. 
As I can see all 4 devices on the Smart-M Air App I can tell that status changes via the "setstat" node work on all machines.  Now I was wondering whether this has something to do with the node or with my hardware. I switched the wifi on the respective devices on and off but with no impact on the result. 
Do you have an idea what could be the reason for this?

Thanks a lot in advance and best regards,
LG

**Comment by Programie** [comment]
Hi,
thanks for letting me know that you have some issues with the node. Most of the effort is not my work, as I just ported the [ioBroker implementation](https://github.com/wolkeSoftware/ioBroker.woso_mitsu_aircon_rac) to Node-RED.

Are your wall units of the same model? And are they all running the same firmware version (I guess, you can find that in the Smart-M Air App)?

In some cases, it is required to specify the operator ID and device ID. But if all of your devices are of the same model, are running the same firmware version and some of them are working fine, it's probably not caused by that.

You could also try to manually sent the "getAirconStat" command to the device which should look like the following:

```
# curl http://<ip-or-host-of-your-device>:51443 -X POST -d '{"apiVer":"1.0","command":"getAirconStat","operatorId":"","deviceId":"","timestamp":0}' -H "Content-Type: application/json;charset=UTF-8" -s | jq
{
  "command": "getAirconStat",
  "apiVer": "1.0",
  "operatorId": "",
  "deviceId": "",
  "timestamp": 0,
  "result": 1,
  "contents": {
    "airconId": "ec0baef691ee",
    "airconStat": "AACqjq7/AAAAAIASCgAAAAAAAf////+8yoEECAYumwAAiAAAAgAAAAAAAAOAIJv/gBB1/5QQAQAEjQ==",
    "logStat": 0,
    "updatedBy": "local",
    "expires": 1697232084,
    "ledStat": 1,
    "autoHeating": 0,
    "highTemp": "AB",
    "lowTemp": "66",
    "firmType": "WF-RAC",
    "wireless": {
      "firmVer": "010"
    },
    "mcu": {
      "firmVer": "123"
    },
    "timezone": "Europe/Berlin",
    "remoteList": [
      "",
      "",
      "",
      ""
    ],
    "numOfAccount": 2
  }
}
```

**Comment by LordenGreen** [comment]
Hi Michael, thanks for the instant reply.I have four machines. 3 are the same and one is a bit bigger. Two of the smaller ones work fine.All are in the latest firmware according to the app. I’ll give it a try with the request you’ve provided.What is interesting is that you state numofaccount = 2. I thinks it’s always 1.Let me check and I’ll get back to you.Cheers and thanks for your help,LGAm 17.10.2023 um 10:35 schrieb Michael Wieland ***@***.***>:﻿
Hi,
thanks for letting me know that you have some issues with the node. Most of the effort is not my work, as I just ported the ioBroker implementation to Node-RED.
Are your wall units of the same model? And are they all running the same firmware version (I guess, you can find that in the Smart-M Air App)?
In some cases, it is required to specify the operator ID and device ID. But if all of your devices are of the same model, are running the same firmware version and some of them are working fine, it's probably not caused by that.
You could also try to manually sent the "getAirconStat" command to the device which should look like the following:
# curl http://<ip-or-host-of-your-device>:51443 -X POST -d '{"apiVer":"1.0","command":"getAirconStat","operatorId":"","deviceId":"","timestamp":0}' -H "Content-Type: application/json;charset=UTF-8" -s | jq
{
  "command": "getAirconStat",
  "apiVer": "1.0",
  "operatorId": "",
  "deviceId": "",
  "timestamp": 0,
  "result": 1,
  "contents": {
    "airconId": "ec0baef691ee",
    "airconStat": "AACqjq7/AAAAAIASCgAAAAAAAf////+8yoEECAYumwAAiAAAAgAAAAAAAAOAIJv/gBB1/5QQAQAEjQ==",
    "logStat": 0,
    "updatedBy": "local",
    "expires": 1697232084,
    "ledStat": 1,
    "autoHeating": 0,
    "highTemp": "AB",
    "lowTemp": "66",
    "firmType": "WF-RAC",
    "wireless": {
      "firmVer": "010"
    },
    "mcu": {
      "firmVer": "123"
    },
    "timezone": "Europe/Berlin",
    "remoteList": [
      "",
      "",
      "",
      ""
    ],
    "numOfAccount": 2
  }
}

**Comment by Programie** [comment]
The `numOfAccount` in my response seems to be caused because I connected the app multiple times which created another "account". I used the app to initially setup my devices, then removed the app again and later tried something for which I had to reinstall the app again. But that's just a guess.

**Comment by Programie** [comment]
As there was no response, I will close this issue.

Please let me know if you are still experiencing this issue or anything else related to this node.
